### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by mzpqnxow** [spitz-dan-l/postgres_binary_parser#2]
I noticed some build issues when building with cPython 3.7. I fixed them (they were just very minor interface changes) if you're still maintaining this I'm happy to send a PR. Really just curious if you're still maintaining this or not as it caught my eye recently

Thanks

EDIT: Actually, all that's really needed is to regenerated the `psql_binary.c` file with a more recent version of Cython- so I don't think you really need/want a PR for this (though still happy to help)

**Comment by spitz-dan-l** [comment]
Hi there, thanks for the interest.

Not actively maintaining, no longer in active use, though I would be happy to accept PRs. (You're also welcome to fork this and start maintaining it yourself.) I see from recent issues that there are some very simple bugs that can be easily fixed. I may spend a little time get this into a state where folks can at least use it without modification! Any PRs towards that end would of course be much appreciated.

**Comment by spitz-dan-l** [comment]
@mzpqnxow I just fixed the broken build. Thanks again for your interest!

**Comment by mzpqnxow** [comment]
Cheers
