### ISSUE TITLE
Any interest in supporting INET/CIDR and/or JSONB types?

### ISSUE THREAD

**Issue by mzpqnxow** [spitz-dan-l/postgres_binary_parser#3]
Do you have any interest in developing (or accepting PRs for) supporting INET/CIDR and/or JSONB types?

**Comment by spitz-dan-l** [comment]
Hey there, as I mentioned in the #2 I'm not actively maintaining this, but happy to accept PRs (and you're welcome to fork). Would definitely accept PRs for new data types.
